version: '3.8'

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile.demo
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DEMO_MODE=true
      - DEMO_PASSWORD=AndyDemo2025!
      - DATABASE_URL=postgresql://demo:demo@demo-db:5432/demo
      - REDIS_URL=redis://demo-redis:6379
    depends_on:
      - demo-db
      - demo-redis
    restart: unless-stopped

  demo-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "5432:5432"
    volumes:
      - demo_db_data:/var/lib/postgresql/data
    restart: unless-stopped

  demo-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - demo_redis_data:/data
    restart: unless-stopped

volumes:
  demo_db_data:
  demo_redis_data:
